typedef struct Node;
Node *create_node(int n);
void delete_node(Node *n);
typedef struct LinkedList;
LinkedList *create_linked_list();
void append_to_linked_list(LinkedList *lst, int x);
int remove_first_from_linked_list(LinkedList *lst);
int linked_list_size(LinkedList *lst);
void delete_linked_list(LinkedList *lst);
typedef struct Queue;
Queue *create_queue();
int queue_size(Queue *q);
void enqueue(Queue *q, int n);
int dequeue(Queue *q);
void delete_queue(Queue *q);
typedef struct Graph;
Graph create_graph(int num_vertices);
void add_edge(Graph *g, int edge[1][2]);
void delete_graph(Graph *g);
int *shortest_path(int source, Graph *g);
int average_shortest_path_length(Graph *g);
typedef struct SkipNode;
SkipNode *create_skip_node(int val, int height);
typedef struct SkipList;
SkipList *create_skip_list(int MAX_LEVEL);
SkipNode *search_skip_list(SkipList *lst, int key);
void insert_into_skip_list(SkipList *lst, int key);
void delete_from_skip_list(SkipList *lst, int key);