typedef struct Node;
Node *create_node(int n);
void delete_node(Node *n);
void add_first(Node *head, int n);
void add_last(Node *head, int n);
int remove_first(Node *head);
int remove_last(Node *head);
void delete_linked_list(Node *head);
typedef struct Queue;
int size(Queue q);
void enqueue(Queue *q, int n);
int dequeue(Queue *q);
Queue create_queue();
void delete_queue(Queue *q);
typedef struct Graph;
Graph create_graph(int num_vertices, int num_edges, int **edge_list);
void delete_graph(Graph *g);
int *shortest_path(int source, Graph g);
int average_shortest_path_length(Graph g);
typedef struct ArrayHeap;
int heap_size(ArrayHeap h);
double top(ArrayHeap h);
ArrayHeap create_heap(int heap_type);
void heapify(double *arr);
void heap_push(ArrayHeap h, double x);
double heap_pop(ArrayHeap h);