typedef struct Node;
Node *create_node(int n);
void delete_node(Node *n);
typedef struct LinkedList;
LinkedList *create_linked_list();
void append_to_linked_list(LinkedList *lst, int x);
int remove_first_from_linked_list(LinkedList *lst);
int linked_list_size(LinkedList *lst);
void delete_linked_list(Node *head);
typedef struct Queue;
int size(Queue q);
void enqueue(Queue *q, int n);
int dequeue(Queue *q);
Queue create_queue();
void delete_queue(Queue *q);
typedef struct Graph;
Graph create_graph(int num_vertices);
void delete_graph(Graph *g);
void add_edge(Graph *g, int edge[1][2]);
int *shortest_path(int source, Graph g);
int average_shortest_path_length(Graph g);
typedef struct ArrayHeap;
int heap_size(ArrayHeap h);
double top(ArrayHeap h);
ArrayHeap create_heap(int heap_type);
void heapify(double *arr, int heap_type, int length, int i);
void heap_push(ArrayHeap h, double x);
double heap_pop(ArrayHeap h);